services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.docker
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - ./apps/web/.env
      - ./apps/web/.env.docker
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - api

volumes:
  db:
    driver: local
