version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fit
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data


  api:
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    env_file:
      - .env.docker-compose
    command: yarn start:dev
    depends_on:
      - db


  frontend:
    build:
      context: ./apps/frontend/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - .env.docker-compose

    command: yarn dev
    depends_on:
      - api


  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend


volumes:
  db:
    driver: local
