name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cypress Install
        uses: cypress-io/github-action@v5.0.7
        with:
          runTests: false

      # - name: Setup Node.js Environment
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.12.1
      #     cache: "yarn"

      - name: Install Depedencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Cypress info
        run: yarn cypress info

      - name: Start
        run: yarn start:frontend &

      - name: E2E Tests
        uses: cypress-io/github-action@v5.0.7
        with:
          browser: chrome
          record: true
          working-directory: apps/frontend

      # - name: Start
      #   run: yarn start:frontend &

      # - name: Test E2E
      #   run: yarn test

  # ui-chrome-tests:
  #   name: E2E Tests
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cypress/browsers:node18.12.0-chrome107
  #     options: --user 1001
  #   needs: build
